FROM docker.elastic.co/elasticsearch/elasticsearch:8.10.2

ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

COPY elasticsearch-analysis-ik-8.10.2.zip /tmp/ik.zip

RUN cd /tmp && unzip -q -o ik.zip && mkdir -p /usr/share/elasticsearch/plugins/analysis-ik && cp -r plugin-descriptor.properties plugin-security.policy config *.jar /usr/share/elasticsearch/plugins/analysis-ik/ 2>/dev/null ; true

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin list
